apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailtrain.fullname" . }}-config
data:
  production.toml: |-
    language="{{ .Values.mailtrain.language }}"

    [www]
    proxy=true

    [mysql]
    host="{{ .Values.mailtrain.mysql.host }}"
    port={{ .Values.mailtrain.mysql.port }}
    user="{{ .Values.mailtrain.mysql.user }}"
    password="{{ .Values.mailtrain.mysql.password }}"
    database="{{ .Values.mailtrain.mysql.database }}"
