apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "znc.fullname" . }}
  labels:
    {{- include "znc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
