name: Helm Docs and CRD updates

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v2
        with:
          # renovate: go-version
          go-version: 1.17.7

      - name: Install helm-docs
        # renovate: datasource=github-releases depName=norwoodj/helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.7.0

      - name: regenerate documentation
        run: $HOME/go/bin/helm-docs

      - name: Commit updated docs
        uses: EndBug/add-and-commit@v8
        with:
          message: "docs: regenerate chart README.md"

          # Only add README.md in charts/ and all subdirectories: https://git-scm.com/docs/git-add#_examples
          add: "charts/**/README.md"

  update-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Remove CRDs
        run: rm charts/kube-prometheus-stack-crds/templates/*

      - name: Get current chart version
        id: chart_version
        run: |
          echo "::set-output name=CHECKOUT_REF::$(sed '/^version:/!d;s/version: //' charts/kube-prometheus-stack-crds/Chart.yaml)"

      - name: Check out prometheus-community/helm-charts
        uses: actions/checkout@v2
        with:
          repository: prometheus-community/helm-charts
          ref: "kube-prometheus-stack-${{ steps.chart_version.outputs.CHECKOUT_REF }}"
          path: kube-prometheus-stack-upstream

      - name: Copy CRDs
        run: cp kube-prometheus-stack-upstream/charts/kube-prometheus-stack/crds/* charts/kube-prometheus-stack-crds/templates/

      - name: Remove kube-prometheus-stack upstream clone
        run: rm -r kube-prometheus-stack-upstream

      - name: show git status
        run: |
          ls -l
          git status
          git remote -v

      - name: Commit updated CRDs
        uses: EndBug/add-and-commit@v8
        with:
          message: "chore: update kube-prometheus-stack CRDs"
          add: "charts/kube-prometheus-stack-crds/templates/*"
